name: Deploy to GitHub Pages

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: npm install -g yarn
        run: npm install -g yarn
      - name: yarn --frozen-lockfile
        run: yarn --frozen-lockfile
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn
      - name: Build project
        run: yarn run build
      - name: Export static files
        run: yarn run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: out
